### ISSUE TITLE
Values更新错误

### ISSUE THREAD

**Issue by Jerey-Jobs** [PandaQAQ/LoopScale#1]
在滑动时,有几率值在变但是View没有滑动

是不是手势滑动处理出现问题,<br>
见图片上的重量100g标尺
![loopscale](https://cloud.githubusercontent.com/assets/9072872/22633801/82746268-ec5f-11e6-93d4-f2aa937a8f31.png)

**Comment by PandaQAQ** [comment]
got，发现问题所在尽快修复
